
package com.rolmex.android.oa.ws;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.4
//
// Date Of Creation: 3/15/2013 9:27:09 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

public interface IWsdl2CodeEvents {
    public void Wsdl2CodeStartedRequest();

    public void Wsdl2CodeFinished(String methodName, Object Data);

    public void Wsdl2CodeFinishedWithException(Exception ex);

    public void Wsdl2CodeEndedRequest();
}
